last task
11cfif/spsuace--finalWork pull request #1
Opened 2019-04-22 03:47 UTC by hBuzzy

2019-04-22 06:00 UTC, 11cfif requested changes

2019-04-22 06:00 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/airline/Aircraft.java
> +    private int businesPlaces;
если это не меняется, пишите final

2019-04-22 06:00 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/airline/Airline.java
> + * Баланков Никита
Простите )

2019-04-22 06:00 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/airline/Company.java
> +        this.aircrafts = aircrafts;
Здесь лучше копировать список (чтобы тот кто создал его, не изменил потом, и как следствие он не изменился у вас)

2019-04-22 06:00 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/airline/Company.java
> +    private List<Flight> createFlightList(List<Aircraft> aircrafts, List<Direction> directions) {
это у вас как тест? А почем нельзя сделать тест?)

2019-04-22 06:00 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/airline/TicketDecorator.java
> +public abstract class TicketDecorator extends BaseTicket{
Мне кажется здесь это вообще не нужно.

2019-04-25 10:15 UTC, 11cfif commented
Не хотите идеально сделать задание? Если хотите, могу вас попроверять летом

2019-04-25 15:51 UTC, hBuzzy commented
окей, хочу ;) после зачетов приступлю тогда)

2020-04-25 09:07 UTC, closed without merging