logisticCompany
11cfif/spsuace--finalWork pull request #4
Opened 2019-04-23 19:31 UTC by 6Naci

2019-04-24 07:23 UTC, 11cfif requested changes
Сделайте методы добавления рейса и добавления дня.
Считаем что все рейсы за один день идут.
Тогда при добавлении дня, надо у всех машин (которые задействованы в рейсах( убрать немного ресурса и добавить деньги полученные с этих рейсов

Плюс по классам разнесите все и не забудьте про поля (приватные и где надо финальные)

2019-04-24 07:23 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/logistic/LogisticCompany.java
> +    public class Machine { //машина
Сделайте отдельные классы пожалуйста.

2019-04-24 07:23 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/logistic/LogisticCompany.java
> +        public List<Machine> machineList;
поля должны быть приватные. 
А списки можно сразу инициализировать и сделать финальными. Мы как раз об этом с вами говорили :)

2019-04-24 07:23 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/logistic/LogisticCompany.java
> +                money += machine.price * 0.3;
Думаю можно сделать этот коэфициент внутри класса машины

2019-04-25 06:28 UTC, 11cfif requested changes
И выделите каждый класс в отдельный файл!

2019-04-25 06:28 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/logistic/LogisticCompany.java
> +        public void addFlightDuration(Flight flight) {
вы добавляете день а передаете рейс. Как так?
Тут должно быть итерирование по всем рейсам и пересчет денег не от одного рейса а от всех

2019-04-25 08:53 UTC, 6Naci commented
Я исправил, теперь должно быть верно

2019-04-25 10:14 UTC, closed without merging