Зачетное задание)
11cfif/spsuace--finalWork pull request #5
Opened 2019-04-24 19:59 UTC by RyzhukE

Добрый вечер!

2019-04-24 20:17 UTC, RyzhukE commented
Ой.

2019-04-24 21:54 UTC, 11cfif requested changes
Поправьте и можно будет передать зачетку завтра

2019-04-24 21:54 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/hotels/Hotel.java
> +            if (this.list.get(i).getPlaces() >= places
this тут не нужен

2019-04-24 21:54 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/hotels/Hotel.java
> +    public void OrderNumber(int places, Date date, boolean breafast) {
методы с маленькой буквы

2019-04-24 21:54 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/hotels/HotelNumber.java
> +    private int Price;
с маленькой буквы

2019-04-24 21:54 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/hotels/Hotel.java
> +    private List<HotelNumber> bookedNumbers;
список нигде не инициализирован

2019-04-24 21:54 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/hotels/HotelNumber.java
> +        return  this.Price = countPrice(this.places, this.breakfast);
в две строчки напишите лучше

2019-04-25 06:50 UTC, 11cfif requested changes
Ответьте на вопрос и все

2019-04-25 06:50 UTC, 11cfif commented on src/main/java/ru/spsuace/projects/hotels/HotelNumber.java
> +        this.places -= places;
тут 7 раз используется this. скажите какие this здесь на самом деле нужны а какие нет?
Напишите просто тут

2020-04-25 09:06 UTC, closed without merging